### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by meirgottlieb** [edvenkat/cordova-plugin-keyboard-master1#1]
Hello,

I noticed your comment here https://github.com/cjpearson/cordova-plugin-keyboard/issues/83 and then found this project. I'm having the same issue and this project seems to fix it. What's the status of this project? Do you consider it to be ready for production use?

Thanks!

**Comment by ghost** [comment]
Hi there, 
I have exactly the same problem here. in a form on input focus, the whole body is moving down and up like  HideKeyboard event was triggered and released. Any idea on this issue? Thanks

**Comment by edvenkat** [comment]
@meirgottlieb i will do and update you

**Comment by meirgottlieb** [comment]
Hey @edvenkat, Great. Thanks! I don't know if it's helpful but we branched the original plugin, pulled in the core of your changes, and did some testing on both iOS 11 and 12. You can get the branch here: https://github.com/jsg5116/cordova-plugin-keyboard.git.

**Comment by edvenkat** [comment]
Okay @meirgottlieb that is also fine.

**Comment by hcmac** [comment]
`XtremePush.hitTag('firstname','USER_FIRST_NAME')`
