### ISSUE TITLE
Input type Date is scrolling up after a moment

### ISSUE THREAD

**Issue by TaylorHawkes** [edvenkat/cordova-plugin-keyboard-master1#2]
@edvenkat  - thanks for your work on this, does seem to fix a number of issues.  I did notice that if you try to select a  <input type="date"> it will auto scroll up and you can't select a date. Any ideas on fix for this?

**Comment by TaylorHawkes** [comment]
I actually just forked original repo and only included your changes that fixed specific "black screen issue under the keyboard on IOS 12+": https://github.com/TaylorHawkes/cordova-plugin-keyboard

**Comment by edvenkat** [comment]
@TaylorHawkes In this plugin we have restricted the date range ( from current year-100 to current year - 13). If you don't want please remove that functionality from the code.
